### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by alizainkazmi**
update to use Android-SpinKit:1.2.0.

### CODE REVIEW

**Comment by BertsIdleHands** [comment]
Would be great if we get this merged in soon. All builds broken :'(
@maxs15

**Comment by ErickMaeda** [comment]
Please merge it ASAP!!

**Comment by ErickMaeda** [comment]
Yesterday released a new version with the bugfix https://github.com/maxs15/react-native-spinkit/pull/113.

Just update your `package.json` to `"react-native-spinkit": "^1.2.0"`

**Comment by ErickMaeda** [comment]
Yesterday released a new version with the bugfix https://github.com/maxs15/react-native-spinkit/pull/113.

But this release isn't in npm yet.

**Pull request closed without merging**
