### PR TITLE
Edit README.md and fix rnpm link issue

### PR DESCRIPTION
**Pull request by wkh237**
Hi @maxs15, I found some problems in latest release so I made some changes to correct these problems.

1.I added some information in README.md with my broken english, please feel to give me suggestion if rewrite/edit is necessary :p

2.In last pull request I added RNPM support, but just as I mentioned, RNPM does not automatically adds Jitpack repository to Android project. This means we still have to add it manually otherwise it results in build failure when developers link react-native-spinkit using RNPM. In order make it automatic I added a  node script to add Jitpack repository automatically.

### CODE REVIEW

**Comment by maxs15** [comment]
Great @wkh237, this script is handy indeed !
Your Android guide is great but focused on users using Android studio, maybe it would be better for everyone to understand to talk about modifying the build.gradle & settings.gradle files ?
in android/app/build.gradle:
```
compile project(':react-native-spinkit')
```
in android/settings.gradle
```
include ':react-native-spinkit'
 +project(':react-native-spinkit').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-spinkit/android')
```

**Comment by wkh237** [comment]
Ok @maxs15 , I think you're right, I will preserve the original part :D

**Comment by maxs15** [comment]
PR merged :)
I've created a wiki to explain the manual Android/IOS installation, the README should be cleaner that way

**Comment by wkh237** [comment]
Great ! 👍

**Pull request merged**
