### PR TITLE
Add native spinners from Android-Spinkit

### PR DESCRIPTION
**Pull request by wkh237**
Added an Android project that uses [Android-Spinkit](https://github.com/ybq/Android-SpinKit) so that spinners can have native performance just like iOS ones !

Spinners :

Bounce
Wave
RotatingPlane
WanderingCubes
9CubeGrid
FadingCircleAlt
Pulse
ChasingDots
ThreeBounce
Circle
FoldingCube

also make it possible to link iOS and Android libraries simply use `rnpm`

```
$ rpm link
```
but on Android, after `rnpm link` you still need to add JitPack repository to your android app's `build.gradle` 

```
allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
```

Add `index.android.js` in Example

### CODE REVIEW

**Comment by maxs15** [comment]
This is awesome @wkh237 !!!! :)
The only missing piece we needed  🎉
I just have a few questions:
- Can you confirm me that all the files you committed are necessary (.idea folder, gradle folder ...)? Maybe only necessary for your IDE ?
- Why did you develop another Example instead of using the one we already have ? (It would be easier to manage one cross-platform example instead of 2)

**Comment by wkh237** [comment]
@maxs15 No problem, I'll clean up the android project :D

As for the Android example, because index.android.js was empty, I thought that means the android part will not use the same one in index.ios.js ( after all android still missing Arcs and WordPress spinners ), so I put my test app instead. 

I think it's good to use the same example, I 'll replace index.android.js with the iOS example :)

**Comment by maxs15** [comment]
Perfect 👍 
Well index.android.js was requiring index.ios.js, kind of stupid I admit (we could rename it index.js) but everything should work without modifying the example.
Thanks again for the good work !

**Comment by wkh237** [comment]
@maxs15 I've updated my master branch for the changes :D

**Comment by maxs15** [comment]
Awesome, I'm going to check that.
I'm getting an error when running the Example app, seems like I can't fetch the Android-SpinKit dependency.
Still trying to figure out why

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.github.ybq:Android-SpinKit:1.0.4.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.pom
         https://jcenter.bintray.com/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.jar
         file:/Users/maxs/Documents/Perso/Github/personal/react-native-spinkit/Example/node_modules/react-native/android/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.pom
         file:/Users/maxs/Documents/Perso/Github/personal/react-native-spinkit/Example/node_modules/react-native/android/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.jar
         file:/Users/maxs/Documents/SDK/ANDROID/extras/android/m2repository/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.pom
         file:/Users/maxs/Documents/SDK/ANDROID/extras/android/m2repository/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.jar
         file:/Users/maxs/Documents/SDK/ANDROID/extras/google/m2repository/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.pom
         file:/Users/maxs/Documents/SDK/ANDROID/extras/google/m2repository/com/github/ybq/Android-SpinKit/1.0.4/Android-SpinKit-1.0.4.jar
     Required by:
         Example:app:unspecified > Example:react-native-spinkit:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by wkh237** [comment]
@maxs15 because Android-Spinkit uses jitpack not default repository, after rnpm link you still have to manually add 

'maven { url "https://jitpack.io" }'

to app's android build.gradle just like what I described in the first comment.

(because I don't know how to make this automatic :/ )

I 've tested this on different machines several times, and I think it should work properly, I'll try it again later :D

**Comment by maxs15** [comment]
I've finally succeeded to build the app, the problem was ``maven { url "https://jitpack.io" }`` in Example/android/build.gradle was defined in the ``buildscript``property instead of ``allprojects``.

Now I'm gonna have to find why the app quit unexpectedly (I'm getting an alert "Unfortunately, Example has stopped") when I'm running the app on my phone with the library.
If I unlink the library the app is working again

**Comment by maxs15** [comment]
Could you send me your build.gradle ?
I want to make sure everything is right

**Comment by wkh237** [comment]
@maxs15 I think you're right, I should move `maven { url "https://jitpack.io" }` into `allprojects ` block.

As for the app crash problem, does it happens when you click `change color` button several times? Android color attribute only accepts  six-digit hexadecimal representation, perhaps this is the reason ?

**Comment by maxs15** [comment]
No it's on the app start, I don't even see anything..
It should something missing in my configuration if you're able to start your app properly without any issue

**Comment by wkh237** [comment]
Hi @maxs15 , I'm locating the issue, are you running the app with `release` configuration ? I could only reproduce this issue when I change `Build Variant` to `release` in Android Studio.



After the app crashes (on the app start just like you described),
I find last logs before it crashes by command `adb logcat`

```
E/        (30771): Unable to load script from assets: index.android.bundle
E/AndroidRuntime(30771): FATAL EXCEPTION: mqt_js
E/AndroidRuntime(30771): Process: com.example, PID: 30771
E/AndroidRuntime(30771): java.lang.RuntimeException: Couldn't get the native call queue: bridge configuration isn't available. This shouldn't be possible. Congratulations.
E/AndroidRuntime(30771): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime(30771): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(30771): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(30771): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime(30771): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(30771): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
E/AndroidRuntime(30771): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  728):   Force finishing activity com.example/.MainActivity
E/EGL_emulation(  713): tid 713: eglCreateSyncKHR(1181): error 0x3004 (EGL_BAD_ATTRIBUTE)
```

I think this is the reason, because there's no `assets` folder in Example project, not to mention the bundle file `index.android.bundle`

```
E/        (30771): Unable to load script from assets: index.android.bundle
```

If we're using debug mode, the app fetches bundle from react-native packager server instead of assets folder inside itself, so it won't crash.

In order to generate offline bundles, I followed procedure in [official document](https://facebook.github.io/react-native/docs/signed-apk-android.html#content)

Go to the root folder of Example app and run this command

```shell
# do execute ./gradlew installRelease in android folder, that will use an incorrect CWD
cd android && ./gradlew installRelease
```
And the app starts without any problem.

**Comment by maxs15** [comment]
Thanks for looking @wkh237.
Unfortunately this is not the issue, I'm running the app in debug mode using ``react-native run-android``
I'm getting that error using ``adb logcat``
```
E/AndroidRuntime( 3416): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 3416): Process: com.example, PID: 3416
E/AndroidRuntime( 3416): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 3416): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 3416): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 3416): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 3416): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 3416): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 3416): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 3416): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 3416): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 3416): Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.net.ConnectivityManagerCompat.<init>()' is inaccessible to class 'com.facebook.react.modules.netinfo.NetInfoModule' (declaration of 'com.facebook.react.modules.netinfo.NetInfoModule' appears in /data/app/com.example-2/base.apk)
E/AndroidRuntime( 3416): 	at com.facebook.react.modules.netinfo.NetInfoModule.<init>(NetInfoModule.java:55)
E/AndroidRuntime( 3416): 	at com.facebook.react.shell.MainReactPackage.createNativeModules(MainReactPackage.java:67)
E/AndroidRuntime( 3416): 	at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:793)
E/AndroidRuntime( 3416): 	at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:730)
E/AndroidRuntime( 3416): 	at com.facebook.react.ReactInstanceManagerImpl.access$600(ReactInstanceManagerImpl.java:91)
E/AndroidRuntime( 3416): 	at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:184)
E/AndroidRuntime( 3416): 	at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:169)
E/AndroidRuntime( 3416): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 3416): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 3416): 	... 4 more
```
There is some issue related to this error on the RN github (like this one: https://github.com/facebook/react-native/issues/7373)
Could you confirm me the version of react-native you're running?
I'm running the example using the RN 0.25.1

Thanks

**Comment by maxs15** [comment]
@wkh237 found the issue.
If I'm removing ``compile 'com.android.support:appcompat-v7:23.3.0`` it's working !
Do you know if we need this library ? Looks like some component like react-native-dialogs (https://github.com/aakashns/react-native-dialogs/blob/master/android/build.gradle) doesn't include it

**Comment by wkh237** [comment]
Hi, @maxs15, it's great to hear that! The RN version I'm using should be the same as yours, I just clone the master branch and install my spinkit from my local repo when testing.

```shell
$ git clone https://github.com/maxs15/react-native-spinkit.git
$ cd react-native-spinkit/Example
$ npm install
$ npm install --save path-to-local-repo
$ rnpm link
$ vim android/build.gradle # open build.gradle and add jitpack repo manually
```

It works fine on my devices (Android 4.4 and 5.0 devices).

The adb log looks like something is changing UI in a non-UI thread, but I can't figure out why android support library make this happen. 

I think this line :

```gradle
compile 'com.android.support:appcompat-v7:23.3.0
```

is unnecessary, it's automatically generated when I create the android library project, and it seems that [Android-Spinkit](https://github.com/ybq/Android-SpinKit) does not use it at all, and neither do I.

**Comment by maxs15** [comment]
Ok, let's figure it out later and merge the PR.

**Comment by maxs15** [comment]
The native android spinners are now available in the release [0.1.0](https://github.com/maxs15/react-native-spinkit/releases/tag/v0.1.0) !
@wkh237 could you check if everything is working on your side using the last version ? Thanks

**Pull request merged**
