### PR TITLE
 Add the sageExtGet function to adapt custom version of buildTools, compileSdk and targetSdk

### PR DESCRIPTION
**Pull request by panda8z**
Add the sageExtGet function to adapt custom version of buildTools, compileSdk and targetSdk

### CODE REVIEW

**Comment by azai91** [comment]
can this be merged? addresses PR https://github.com/maxs15/react-native-spinkit/issues/104 and https://github.com/maxs15/react-native-spinkit/issues/109

**Comment by panda8z** [comment]
> can this be merged? addresses PR #104 and #109

yes  same problem  they should use API 28

**Comment by gtaylor44** [comment]
Same issue. Can this be merged?

**Comment by gtaylor44** [comment]
Another way to get around this issue and have code in source control is to update android\build.gradle under 'allProjects' section to force comipler to use later versions:

```
    subprojects {
        afterEvaluate {
            project ->
                if (project.hasProperty("android")) {
                    android {
                        compileSdkVersion = rootProject.compileSdkVersion
                        buildToolsVersion = rootProject.buildToolsVersion
                    }
                }
        }
    }
```

**Comment by panda8z** [comment]
> Another way to get around this issue and have code in source control is to update android\build.gradle under 'allProjects' section to force comipler to use later versions:
> 
> ```
>     subprojects {
>         afterEvaluate {
>             project ->
>                 if (project.hasProperty("android")) {
>                     android {
>                         compileSdkVersion = rootProject.compileSdkVersion
>                         buildToolsVersion = rootProject.buildToolsVersion
>                     }
>                 }
>         }
>     }
> ```

well， but in this way  minSDK and targetSDK can not  be replace with custom.

**Comment by panda8z** [comment]
> Same issue. Can this be merged?

yes it can be merged

**Comment by maxs15** [comment]
Thanks ! Going to merge it, everything looks good

**Comment by reza7rm** [comment]
> Thanks ! Going to merge it, everything looks good

still not working in 1.3.0

**Pull request merged**
